experiment:
  name: deepDocConfig
  manual_seed: 123

training_dataset_sizes: [20,] #[ 20,40,60,80,100 ]

model_param:
  version: torchvision    # torchvision/original

dataset_params:
  img_root_dir: C:\workspace\dfki-task\Tobacco3482-jpg
  num_workers: 8
  batch_size: 10

logging_params:
  log_dir: C:\workspace\dfki-task\deepDocClassifier\logs\deepDocClassifier

trainer_params:
  gpus: 1
  max_epochs: 1
  #  accelerator: ddp
  precision: 16
#  log_gpu_memory: all
  progress_bar_refresh_rate: 1
  log_every_n_steps: 1
#  limit_train_batches: 1 # set to 0.01 for testing the finetuning step
#  limit_val_batches: 0.02
  limit_test_batches: 0.3